import Paths from "core/paths";
import useAuth from "customHooks/useAuth";
import { getHubRegister } from "features/authFeature/authMutations";
import { GetServerSideProps } from "next";
import { unstable_getServerSession } from "next-auth";
import Head from "next/head";
import { useState } from "react";
import { authOptions } from "./api/auth/[...nextauth]";

function UserCode() {
	const [inputCode, setInputCode] = useState("");
	const [loading, setLoading] = useState(false);

	const handleSubmit = async (e) => {
		try {
			e.preventDefault();

			if (loading) return;
			const json = localStorage.getItem("providerRegisterData");
			const registerProviderData = JSON.parse(json ?? "{}");
			if (Object.keys(registerProviderData).length <= 0) return;

			return;
			setLoading(true);
			const { error } = await getHubRegister({
				userId: inputCode,
				...registerProviderData,
			});
		} finally {
			setLoading(false);
		}
	};
	return (
		<div className="container">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex min-h-screen w-full items-center justify-center">
				<div className="flex justify-between items-center w-3/5">
					<input
						type="text"
						className="w-full bg-gray-100 rounded p-2 mr-0 border focus:outline-none focus:border-blue-500"
						placeholder="Generated Code"
						value={inputCode}
						onChange={(e) => {
							setInputCode(e.target.value);
						}}
					/>

					<button
						type="button"
						onClick={handleSubmit}
						className="btn bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 font-medium rounded"
					>
						Register
					</button>
				</div>
			</div>
		</div>
	);
}

export default UserCode;
