import Hero from "@/components/Hero";
import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>الصفحة الرئيسية</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
		</div>
	);
}
